spring:
  application:
    name: loan-engine-app
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
loan:
  amount-min: 500
  amount-max: 5000
  term-min: 356
  term-max: 2136
  term-extension: 90
  lower-cutoff-time: 00:00:00
  upper-cutoff-time: 06:00:00
